import Link from 'next/link';
import { prisma } from '@/lib/db';
import { formatAmount, txUrl } from '@/lib/chain/config';
import { ReasonText, type ReasonCode } from '@/lib/pipeline/reasonCodes';
import { EmptyState, PageTitle, Panel, StatCard } from '../components';

export default async function AuditPage() {
  const events = await prisma.auditEvent.findMany({ orderBy: { occurredAt: 'desc' }, take: 100, include: { intent: { select: { type: true, status: true } } } });
  const pass = events.filter(event => event.verdict === 'PASS').length;
  const held = events.filter(event => ['FAIL', 'ISOLATE', 'FREEZE'].includes(event.verdict ?? '')).length;
  return <><PageTitle eyebrow="Evidence" title="Immutable audit trail" description="Replay every policy decision from individual check results, reason codes, held amounts, purpose evidence, and settlement context." action={<div className="flex flex-wrap gap-2"><Link href="/api/audit/export?chain=monad" className="rounded-xl bg-ink px-4 py-3 text-xs font-semibold text-white dark:bg-indigo-brand">Download audit PDF</Link><Link href="/dashboard/activity" className="rounded-xl border border-slate-200 px-4 py-3 text-xs font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200">Open activity</Link></div>} />
    <section className="mb-5 grid gap-3 sm:grid-cols-3"><StatCard label="Recorded events" value={events.length} detail="Latest 100 records" /><StatCard label="Pass decisions" value={pass} detail="Checks cleared" tone="green" /><StatCard label="Held decisions" value={held} detail="Fail, isolate, or freeze" tone="amber" /></section>
    <Panel title="Event ledger" subtitle="Append-only database records · held principal remains quarantined">{events.length === 0 ? <EmptyState title="No audit events" body="Every real pipeline evaluation writes a record before settlement can proceed." /> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{events.map(event => { const details = parsePayload(event.payload); const heldAmount = details.amount && ['FAIL', 'ISOLATE', 'FREEZE'].includes(event.verdict ?? '') ? formatAmount(BigInt(details.amount), details.chain ?? 'monad') : null; return <article key={event.id} className="grid gap-3 px-5 py-4 sm:px-6 lg:grid-cols-[150px_1fr_130px_170px] lg:items-center"><div><p className="text-xs font-semibold">{event.eventType}</p><p className="mt-1 font-mono text-[9px] text-slate-400">{event.id.slice(0, 12)}...</p></div><div><p className="text-xs text-slate-600 dark:text-slate-300">{event.reasonCode ? ReasonText[event.reasonCode as ReasonCode] ?? event.reasonCode : event.trigger ?? 'Recorded system event'}</p><p className="mt-1 text-[10px] text-slate-400">{event.intent?.type ?? 'SYSTEM'} / {event.intent?.status ?? 'N/A'}{heldAmount ? ` · Held ${heldAmount} aUSDC` : ''}</p>{heldAmount && <p className="mt-1 text-[10px] font-medium text-amber-700 dark:text-amber-300">Principal remains quarantined until the issue is resolved.</p>}{details.recipient && <p className="mt-1 font-mono text-[9px] text-slate-400">Recipient {details.recipient}</p>}{details.purpose && <p className="mt-1 text-[10px] font-medium text-indigo-brand">Purpose · {details.purpose}</p>}</div><div className="flex flex-col items-start gap-2"><span className={`w-fit rounded-full px-2.5 py-1 text-[9px] font-bold ${event.verdict === 'PASS' ? 'bg-emerald-50 text-emerald-700' : event.verdict === 'FREEZE' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700'}`}>{event.verdict ?? 'RECORDED'}</span>{details.txHash && <a className="text-[10px] font-semibold text-indigo-brand" href={txUrl(details.txHash, details.chain ?? 'monad')} target="_blank" rel="noreferrer">View explorer receipt</a>}</div><time className="text-[10px] text-slate-400">{event.occurredAt.toISOString()}</time></article>; })}</div>}</Panel>
  </>;
}

function parsePayload(value: string): { amount?: string; chain?: string; txHash?: string; recipient?: string; purpose?: string } {
  try { const parsed = JSON.parse(value) as Record<string, unknown>; const purpose = parsed.purpose && typeof parsed.purpose === 'object' ? parsed.purpose as Record<string, unknown> : undefined; return { amount: typeof parsed.amount === 'string' ? parsed.amount : undefined, chain: typeof parsed.chain === 'string' ? parsed.chain : undefined, txHash: typeof parsed.txHash === 'string' ? parsed.txHash : undefined, recipient: typeof parsed.recipient === 'string' ? parsed.recipient : typeof parsed.recipientCvi === 'string' ? parsed.recipientCvi : undefined, purpose: purpose && typeof purpose.type === 'string' ? `${purpose.type}${typeof purpose.reference === 'string' && purpose.reference ? ` · ${purpose.reference}` : ''}` : undefined }; } catch { return {}; }
}
