'use client';
import { useEffect, useState } from 'react';

type EventRow = { id:string; eventType:string; trigger:string|null; verdict:string|null; reasonCode:string|null; occurredAt:string; intentId:string|null };
export function LiveOversight({ chain, initial, counterparties }: { chain:string; initial:EventRow[]; counterparties:string[] }) {
  const [events,setEvents]=useState(initial); const [connected,setConnected]=useState(false); const [address,setAddress]=useState(counterparties[0]??''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  useEffect(()=>{const controller=new AbortController();const after=initial[0]?.occurredAt??new Date().toISOString();void (async()=>{try{const response=await fetch(`/api/events/stream?chain=${encodeURIComponent(chain)}&after=${encodeURIComponent(after)}`,{signal:controller.signal});if(!response.ok||!response.body)throw new Error('stream unavailable');setConnected(true);const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';while(true){const part=await reader.read();if(part.done)break;buffer+=decoder.decode(part.value,{stream:true});const frames=buffer.split('\n\n');buffer=frames.pop()??'';for(const frame of frames){if(!frame.includes('event: audit'))continue;const data=frame.split('\n').find(line=>line.startsWith('data: '))?.slice(6);if(data){const event=JSON.parse(data) as EventRow;setEvents(current=>[event,...current.filter(row=>row.id!==event.id)].slice(0,12));}}}}catch(error){if(!controller.signal.aborted)setConnected(false);}})();const poll=setInterval(async()=>{try{const response=await fetch(`/api/events/stream?chain=${encodeURIComponent(chain)}&snapshot=1`,{cache:'no-store'});if(!response.ok)return;const data=await response.json() as {events:EventRow[]};setEvents(data.events);setConnected(true);}catch{}},500);return()=>{controller.abort();clearInterval(poll)};},[chain]);
  async function freeze(){setBusy(true);setMessage('');const response=await fetch('/api/freeze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chain,address,reason:'Operator compliance hold'})});const result=await response.json();setMessage(result.frozen?'Freeze confirmed. Live cascade recorded.':result.detail??result.error);setBusy(false)}
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><header className="flex items-center justify-between border-b border-slate-100 px-6 py-4 dark:border-slate-800"><div><h2 className="text-sm font-semibold">Live decision stream</h2><p className="mt-1 text-xs text-slate-500">Append-only pipeline events, pushed without refresh</p></div><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${connected?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{connected?'LIVE':'CONNECTING'}</span></header><div className="divide-y divide-slate-100 dark:divide-slate-800">{events.map(event=><div key={event.id} className="grid gap-2 px-6 py-4 sm:grid-cols-[110px_1fr_100px] sm:items-center"><span className="text-xs font-semibold">{event.eventType}</span><div><p className="text-xs text-slate-600 dark:text-slate-300">{event.trigger??'SYSTEM'}</p><p className="mt-1 text-[10px] text-slate-400">{new Date(event.occurredAt).toLocaleTimeString()} {event.reasonCode?` / ${event.reasonCode}`:''}</p></div><span className={`w-fit rounded-full px-2 py-1 text-[9px] font-bold ${event.verdict==='PASS'?'bg-emerald-50 text-emerald-700':event.verdict==='FREEZE'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{event.verdict??'RECORDED'}</span></div>)}</div></section>
    <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-red-600">Compliance control</p><h2 className="mt-2 text-base font-semibold">Freeze counterparty</h2><p className="mt-2 text-xs leading-5 text-slate-500">Revokes the A-Pass, freezes every active relationship, and writes the cascade to the stream.</p><select value={address} onChange={event=>setAddress(event.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 bg-transparent px-3 py-3 font-mono text-xs dark:border-slate-700"><option value="">Select a pending counterparty</option>{counterparties.map(value=><option key={value}>{value}</option>)}</select><button disabled={!address||busy} onClick={freeze} className="mt-3 w-full rounded-xl bg-red-600 px-4 py-3 text-xs font-semibold text-white disabled:opacity-50">{busy?'Freezing and cascading…':'Freeze and cascade'}</button>{message&&<p role="status" className="mt-3 text-xs text-slate-600 dark:text-slate-300">{message}</p>}</section><Lineage events={events}/></div>
  </div>;
}
function Lineage({events}:{events:EventRow[]}){const rows=events.slice(0,4).reverse();return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-sm font-semibold">Settlement lineage</h2><div className="mt-5 space-y-0">{rows.map((event,index)=><div key={event.id} className="flex gap-3"><div className="flex flex-col items-center"><span className={`h-3 w-3 rounded-full ring-4 ${event.verdict==='FREEZE'?'bg-red-500 ring-red-50':'bg-indigo-500 ring-indigo-50'}`}/>{index<rows.length-1&&<span className="h-10 w-px bg-slate-200"/>}</div><div className="-mt-1 pb-4"><p className="text-xs font-semibold">{event.eventType}</p><p className="mt-1 text-[10px] text-slate-400">{event.trigger??'SYSTEM'} / {event.verdict??'RECORDED'}</p></div></div>)}</div></section>}
