import Image from 'next/image';
import Link from 'next/link';
import { ThemeToggle } from './components/ThemeToggle';

const features = [
  ['Intent engine', 'Humans and AI agents declare outcomes instead of signing raw transfers. Certus authorizes each movement.'],
  ['Milestone escrow', 'Every release is re-screened. A credential change can freeze the next milestone before value moves.'],
  ['Isolation ring', 'One refused recipient never collapses an entire batch. Clean rows continue, refused value stays preserved.'],
  ['Audit provenance', 'Every evaluation becomes an immutable event with check evidence, reason codes, and transaction lineage.'],
  ['Recurring controls', 'Subscription epochs re-enter the same compliance chokepoint instead of relying on stale approval.'],
  ['Payment links', 'Identity and asset eligibility are checked when a link is opened, not merely when it is created.'],
  ['Payroll provenance', 'Signed source-of-funds evidence connects every payout to its verified identity, asset, and settlement checks.'],
  ['Optional yield quarantine', 'On Monad testnet, the fixed-rate demo vault stops accrual and quarantines yield beside principal when trust fails.'],
  ['Identity track record', 'Completed verified intents establish the evidence foundation for differentiated settlement terms.'],
];

export default function LandingPage() {
  return <main className="min-h-screen overflow-hidden bg-[#f8f9fc] text-ink dark:bg-[#080b12] dark:text-slate-100">
    <header className="relative z-20 border-b border-slate-200/70 bg-white/70 backdrop-blur-xl dark:border-slate-800 dark:bg-[#0b0f19]/75"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center gap-3"><Image src="/certus-mark.svg" width={38} height={38} alt="Certus" priority/><div><div className="text-base font-bold tracking-tight">Certus</div><div className="text-[10px] text-slate-400">Policy-gated payments</div></div></Link><nav className="hidden items-center gap-7 text-xs font-medium text-slate-500 md:flex"><a href="#platform" className="hover:text-ink">Payment intents</a><a href="#control" className="hover:text-ink">Continuous checks</a><a href="#proof" className="hover:text-ink">Proof</a></nav><div className="flex items-center gap-2"><ThemeToggle/><Link href="/dashboard" className="rounded-xl bg-ink px-4 py-2.5 text-xs font-semibold text-white shadow-[0_8px_24px_rgba(13,16,48,0.18)] transition hover:-translate-y-0.5 dark:bg-indigo-brand">Open payment app</Link></div></div></header>

    <section className="relative"><div className="absolute inset-x-0 top-0 -z-0 h-[650px] bg-[radial-gradient(circle_at_72%_10%,rgba(108,123,255,0.22),transparent_32rem)]"/><div className="relative mx-auto grid max-w-7xl gap-14 px-5 pb-24 pt-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:pb-32 lg:pt-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-white px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.16em] text-indigo-brand shadow-sm"><span className="h-1.5 w-1.5 rounded-full bg-indigo-brand"/>Policy-gated payment app</div><h1 className="mt-7 max-w-3xl text-5xl font-semibold leading-[1.02] tracking-[-0.055em] sm:text-6xl lg:text-[72px]">Declare the payment. Certus decides if value moves.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-600">Certus is a payment app for people and AI agents that releases USDC or verified aUSDC only after live identity, asset, and spending-policy checks pass.</p><div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/dashboard/send" className="rounded-xl bg-indigo-brand px-5 py-3 text-sm font-semibold text-white shadow-[0_12px_30px_rgba(91,99,232,0.28)] transition hover:-translate-y-0.5">Declare an intent</Link><a href="#control" className="rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700 shadow-sm hover:border-slate-300">See how it works</a></div><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 text-[11px] font-medium text-slate-500"><span className="flex items-center gap-2"><i className="h-1.5 w-1.5 rounded-full bg-emerald-500"/>Four live checks</span><span className="flex items-center gap-2"><i className="h-1.5 w-1.5 rounded-full bg-indigo-brand"/>Humans and AI agents</span><span className="flex items-center gap-2"><i className="h-1.5 w-1.5 rounded-full bg-amber-500"/>Fail-closed execution</span></div></div>
      <HeroConsole />
    </div></section>

    <section id="platform" className="border-y border-slate-200/80 bg-white py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-indigo-brand">One control plane</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Every settlement path enters the same policy chokepoint.</h2><p className="mt-4 text-sm leading-6 text-slate-600">The product does not bolt compliance onto payment flows. Compliance is the mechanism that authorizes each movement of value.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([title,body],i)=><article key={title} className="group rounded-2xl border border-slate-200 bg-[#fbfbfd] p-6 transition hover:-translate-y-1 hover:border-indigo-200 hover:bg-white hover:shadow-[0_18px_50px_rgba(15,23,42,0.07)]"><div className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-brand/10 text-xs font-bold text-indigo-brand">0{i+1}</div><h3 className="mt-5 text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p></article>)}</div></div></section>

    <section id="control" className="bg-ink py-24 text-white"><div className="mx-auto grid max-w-7xl gap-14 px-5 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-indigo-300">Continuous, not one-time</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.045em]">A valid identity yesterday cannot authorize a payment today.</h2><p className="mt-5 text-sm leading-7 text-slate-300">Certus re-runs the full decision at every milestone, batch address, subscription epoch, and payment-link open. If trust changes, settlement changes with it.</p><Link href="/dashboard/audit" className="mt-7 inline-flex rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-ink">Inspect audit controls</Link></div><Pipeline /></div></section>

    <section id="proof" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-5 lg:grid-cols-2"><ProofCard number="01" label="The red row" title="Nine settle. One isolates. The batch survives." body="Each payroll recipient is evaluated independently. A missing credential isolates only that row while eligible recipients settle with signed provenance." tone="indigo"/><ProofCard number="02" label="The mid-contract freeze" title="Trust changes. Every linked flow responds." body="A revoked supplier identity freezes the next milestone, quarantines principal and yield, and halts the next subscription epoch." tone="amber"/></div></div></section>

    <section className="px-5 pb-24 lg:px-8"><div className="mx-auto max-w-7xl overflow-hidden rounded-[28px] bg-gradient-to-br from-indigo-brand to-[#7682ff] px-7 py-12 text-white shadow-[0_24px_70px_rgba(91,99,232,0.25)] sm:px-12 lg:flex lg:items-center lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-indigo-100">Protected payments</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]">Declare your next payment intent.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-indigo-100">Send, escrow, schedule, or disburse value while Certus continuously verifies who can receive it and why.</p></div><Link href="/dashboard/send" className="mt-7 inline-flex rounded-xl bg-white px-5 py-3 text-sm font-semibold text-indigo-brand shadow-lg lg:mt-0">Send a payment</Link></div></section>

    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div className="flex items-center gap-2.5"><Image src="/certus-mark.svg" width={28} height={28} alt=""/><span className="text-sm font-bold">Certus</span></div><p className="text-[11px] text-slate-400">Continuous compliance for verified settlement across configured chains.</p></div></footer>
  </main>;
}

function HeroConsole(){return <div className="relative"><div className="absolute -inset-8 rounded-full bg-indigo-brand/10 blur-3xl"/><div className="relative overflow-hidden rounded-[24px] border border-white/80 bg-white shadow-[0_30px_90px_rgba(44,49,110,0.18)]"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-red-300"/><span className="h-2.5 w-2.5 rounded-full bg-amber-300"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-300"/></div><span className="text-[9px] font-bold uppercase tracking-[0.15em] text-slate-400">Moment A</span></div><div className="p-5"><div className="flex items-end justify-between"><div><p className="text-[10px] text-slate-400">Payroll batch</p><p className="mt-1 text-xl font-semibold">10 recipients</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[9px] font-bold text-emerald-700">9 RELEASED</span></div><div className="mt-6 space-y-2">{Array.from({length:10}).map((_,i)=><div key={i} className={`flex items-center justify-between rounded-xl px-3 py-2.5 ${i===6?'bg-red-50 ring-1 ring-inset ring-red-100':'bg-slate-50'}`}><div className="flex items-center gap-3"><span className={`h-2 w-2 rounded-full ${i===6?'bg-red-500':'bg-emerald-500'}`}/><span className="font-mono text-[10px] text-slate-500">0x{(8120+i).toString(16)}…{(4410+i).toString(16)}</span></div><span className={`text-[9px] font-bold ${i===6?'text-red-700':'text-emerald-700'}`}>{i===6?'NO CVI · ISOLATED':'PASS'}</span></div>)}</div><p className="mt-4 text-[9px] leading-4 text-slate-400">Illustrative product view. Live console displays only database-backed settlement records.</p></div></div></div>}

function Pipeline(){const rows=[['01','Sender CVI','Active, eligible identity'],['02','Recipient CVI','Verified counterparty'],['03','CVA rules','Asset transfer constraints'],['04','Institutional policy','Budget, role, time window']];return <div className="rounded-3xl border border-white/10 bg-white/[0.055] p-5 backdrop-blur sm:p-7">{rows.map(([n,title,body],i)=><div key={n} className={`flex items-center gap-4 py-4 ${i<3?'border-b border-white/10':''}`}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white/10 font-mono text-xs text-indigo-200">{n}</span><div className="flex-1"><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-slate-400">{body}</p></div><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[9px] font-bold text-emerald-300">REQUIRED</span></div>)}<div className="mt-5 rounded-xl bg-white p-4 text-ink"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-slate-400">Decision</p><p className="mt-2 text-sm font-semibold">PASS · FAIL · ISOLATE · FREEZE</p></div></div>}

function ProofCard({number,label,title,body,tone}:{number:string;label:string;title:string;body:string;tone:'indigo'|'amber'}){return <article className={`rounded-[24px] border p-7 sm:p-9 ${tone==='indigo'?'border-indigo-100 bg-indigo-50/50':'border-amber-100 bg-amber-50/60'}`}><div className="flex items-center justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl text-xs font-bold ${tone==='indigo'?'bg-indigo-brand text-white':'bg-amber-500 text-white'}`}>{number}</span><span className={`text-[9px] font-bold uppercase tracking-[0.17em] ${tone==='indigo'?'text-indigo-brand':'text-amber-700'}`}>{label}</span></div><h3 className="mt-12 max-w-md text-2xl font-semibold tracking-[-0.035em]">{title}</h3><p className="mt-3 max-w-lg text-sm leading-6 text-slate-600">{body}</p></article>}
