import fs from 'node:fs';
import path from 'node:path';
import { createPublicClient, createWalletClient, http, parseAbi, parseUnits, type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { assets } from '../src/lib/cleanverse/cva';
import { chainConfig, defaultChain } from '../src/lib/chain/config';

if (process.env.CONFIRM_CUSTODIED_YIELD_AUTH !== 'YES') throw new Error('Set CONFIRM_CUSTODIED_YIELD_AUTH=YES to authorize the testnet pilot.');
const chainKey = defaultChain();
if (chainKey !== 'monad') throw new Error('Custodied yield pilot is pinned to Monad testnet');
const network = chainConfig(chainKey);
const key = process.env.DEPLOYER_PRIVATE_KEY as Hex | undefined;
if (!key) throw new Error('DEPLOYER_PRIVATE_KEY missing');
const account = privateKeyToAccount(key);
const deployment = JSON.parse(fs.readFileSync(path.resolve('deployments', `${chainKey}.json`), 'utf8'));
const pilot = deployment.contracts?.CertusCustodiedYieldVault?.address as `0x${string}` | undefined;
if (!pilot) throw new Error('Custodied yield pilot is not deployed');
const token = assets(chainKey).aToken as `0x${string}`;
const amount = parseUnits(process.env.CUSTODIED_YIELD_AUTH_AMOUNT ?? '10', network.decimals);
const chain = { id: network.chainId, name: network.label, nativeCurrency: { name: network.nativeSymbol, symbol: network.nativeSymbol, decimals: 18 }, rpcUrls: { default: { http: [network.rpcUrl] } } } as const;
const publicClient = createPublicClient({ chain, transport: http(network.rpcUrl) });
const walletClient = createWalletClient({ account, chain, transport: http(network.rpcUrl) });
const abi = parseAbi(['function approve(address spender, uint256 amount) returns (bool)', 'function balanceOf(address account) view returns (uint256)']);
const balance = await publicClient.readContract({ address: token, abi, functionName: 'balanceOf', args: [account.address] });
if (balance < amount) throw new Error(`Custodian has insufficient aUSDC: ${balance} < ${amount}`);
const tx = await walletClient.writeContract({ address: token, abi, functionName: 'approve', args: [pilot, amount] });
await publicClient.waitForTransactionReceipt({ hash: tx });
deployment.contracts.CertusCustodiedYieldVault.authorizedAmount = amount.toString();
deployment.contracts.CertusCustodiedYieldVault.authorizationTx = tx;
deployment.contracts.CertusCustodiedYieldVault.status = 'testnet-only custodial pilot; A-Pass custodian approved aUSDC payout allowance; not protocol-generated yield';
fs.writeFileSync(path.resolve('deployments', `${chainKey}.json`), `${JSON.stringify(deployment, null, 2)}\n`);
console.log(`Authorized ${process.env.CUSTODIED_YIELD_AUTH_AMOUNT ?? '10'} aUSDC for custodial pilot`);
console.log(`Approval tx: ${tx}`);
