import fs from 'node:fs';
import path from 'node:path';
import { createPublicClient, createWalletClient, http, type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { assets } from '../src/lib/cleanverse/cva';
import { assertEligible, chainConfig, defaultChain } from '../src/lib/chain/config';

const chainKey = defaultChain();
assertEligible(chainKey);
if (chainKey !== 'monad') throw new Error('Sponsored yield demo is pinned to Monad testnet');
const network = chainConfig(chainKey);
const key = process.env.DEPLOYER_PRIVATE_KEY as Hex | undefined;
if (!key) throw new Error('DEPLOYER_PRIVATE_KEY missing');
const account = privateKeyToAccount(key);
const token = assets(chainKey).aToken;
const artifactPath = path.resolve('contracts/out/CertusSponsoredYieldVault.sol/CertusSponsoredYieldVault.json');
if (!fs.existsSync(artifactPath)) throw new Error('Build contracts first: forge build');
const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
const chain = { id: network.chainId, name: network.label, nativeCurrency: { name: network.nativeSymbol, symbol: network.nativeSymbol, decimals: 18 }, rpcUrls: { default: { http: [network.rpcUrl] } } } as const;
const publicClient = createPublicClient({ chain, transport: http(network.rpcUrl) });
const walletClient = createWalletClient({ account, chain, transport: http(network.rpcUrl) });
console.log(`Deploying sponsored testnet yield vault for ${token}`);
const deployTx = await walletClient.deployContract({ abi: artifact.abi, bytecode: artifact.bytecode.object, args: [token] });
const receipt = await publicClient.waitForTransactionReceipt({ hash: deployTx });
if (!receipt.contractAddress) throw new Error('Deployment returned no contract address');
const file = path.resolve('deployments', `${chainKey}.json`);
const deployment = JSON.parse(fs.readFileSync(file, 'utf8'));
deployment.contracts = deployment.contracts ?? {};
deployment.contracts.CertusSponsoredYieldVault = { address: receipt.contractAddress, deployTx, constructorArgs: { token }, owner: account.address, status: 'testnet-only sponsored reserve; not protocol-generated yield' };
deployment.note = `${deployment.note ?? ''} Standalone sponsored yield is testnet-only and reserve-funded by the deployer; it is not APY or production yield.`.trim();
fs.writeFileSync(file, `${JSON.stringify(deployment, null, 2)}\n`);
console.log(`vault: ${receipt.contractAddress}`);
console.log(`deploy tx: ${deployTx}`);
console.log('Reserve remains unseeded until the owner explicitly approves a fundReserve transaction.');
