import fs from 'node:fs';
import path from 'node:path';
import { createPublicClient, createWalletClient, http, parseAbi, parseUnits, type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { assets } from '../src/lib/cleanverse/cva';
import { chainConfig, defaultChain } from '../src/lib/chain/config';

if (process.env.CONFIRM_SPONSORED_YIELD_SEED !== 'YES') throw new Error('Set CONFIRM_SPONSORED_YIELD_SEED=YES to fund the demo reserve.');
const chainKey = defaultChain();
if (chainKey !== 'monad') throw new Error('Sponsored yield demo is pinned to Monad testnet');
const network = chainConfig(chainKey);
const key = process.env.DEPLOYER_PRIVATE_KEY as Hex | undefined;
if (!key) throw new Error('DEPLOYER_PRIVATE_KEY missing');
const account = privateKeyToAccount(key);
const deployment = JSON.parse(fs.readFileSync(path.resolve('deployments', `${chainKey}.json`), 'utf8'));
const vault = deployment.contracts?.CertusSponsoredYieldVault?.address as `0x${string}` | undefined;
if (!vault) throw new Error('Standalone sponsored vault is not deployed');
const token = assets(chainKey).aToken as `0x${string}`;
const amount = parseUnits(process.env.SPONSORED_YIELD_SEED ?? '1', network.decimals);
const chain = { id: network.chainId, name: network.label, nativeCurrency: { name: network.nativeSymbol, symbol: network.nativeSymbol, decimals: 18 }, rpcUrls: { default: { http: [network.rpcUrl] } } } as const;
const publicClient = createPublicClient({ chain, transport: http(network.rpcUrl) });
const walletClient = createWalletClient({ account, chain, transport: http(network.rpcUrl) });
const tokenAbi = parseAbi(['function approve(address spender, uint256 amount) returns (bool)', 'function balanceOf(address account) view returns (uint256)']);
const vaultAbi = parseAbi(['function fundReserve(uint256 amount)']);
const balance = await publicClient.readContract({ address: token, abi: tokenAbi, functionName: 'balanceOf', args: [account.address] });
if (balance < amount) throw new Error(`Deployer has insufficient aUSDC: ${balance} < ${amount}`);
const approval = await walletClient.writeContract({ address: token, abi: tokenAbi, functionName: 'approve', args: [vault, amount] });
await publicClient.waitForTransactionReceipt({ hash: approval });
const funding = await walletClient.writeContract({ address: vault, abi: vaultAbi, functionName: 'fundReserve', args: [amount] });
await publicClient.waitForTransactionReceipt({ hash: funding });
console.log(`Seeded ${process.env.SPONSORED_YIELD_SEED ?? '1'} aUSDC reserve`);
console.log(`Approval tx: ${approval}`);
console.log(`Reserve funding tx: ${funding}`);
